
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: dnwo0719

token:
  access_expiration_time: 864000000
  secret: user_token